# Generated by Django 6.0 on 2026-01-01 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedPDF",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="pdfs/")),
                ("original_filename", models.CharField(max_length=500)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("authors", models.TextField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("extracted_text", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "headline",
                    models.CharField(
                        blank=True, help_text="Your LinkedIn headline", max_length=500
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Your industry/field", max_length=255
                    ),
                ),
                (
                    "tone_preference",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual & Conversational"),
                            ("thought_leader", "Thought Leadership"),
                            ("educational", "Educational"),
                            ("storytelling", "Storytelling"),
                        ],
                        default="professional",
                        max_length=100,
                    ),
                ),
                ("include_emojis", models.BooleanField(default=True)),
                ("include_hashtags", models.BooleanField(default=True)),
                (
                    "post_length_preference",
                    models.CharField(
                        choices=[
                            ("short", "Short (< 500 chars)"),
                            ("medium", "Medium (500-1500 chars)"),
                            ("long", "Long (1500+ chars)"),
                        ],
                        default="medium",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="extracted_images/")),
                ("page_number", models.IntegerField()),
                (
                    "is_figure",
                    models.BooleanField(
                        default=False, help_text="Is this a figure/chart?"
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0, help_text="AI-determined relevance for LinkedIn"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_images",
                        to="generator.uploadedpdf",
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance_score", "page_number"],
            },
        ),
        migrations.AddField(
            model_name="uploadedpdf",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_pdfs",
                to="generator.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="SamplePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The full text of your LinkedIn post"),
                ),
                (
                    "engagement_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional: Notes about engagement (likes, comments) to help prioritize style",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_posts",
                        to="generator.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="AI-generated summary of the paper"),
                ),
                (
                    "post_content",
                    models.TextField(help_text="Generated LinkedIn post content"),
                ),
                (
                    "generated_image_url",
                    models.URLField(blank=True, help_text="URL of AI-generated image"),
                ),
                (
                    "generated_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="generated_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_in_posts",
                        to="generator.extractedimage",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_posts",
                        to="generator.uploadedpdf",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_posts",
                        to="generator.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
