# Generated by Django 6.0 on 2026-01-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0002_userprofile_custom_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpdf",
            name="domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="uploadedpdf",
            name="featured_image_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="uploadedpdf",
            name="source_type",
            field=models.CharField(
                choices=[("pdf", "PDF File"), ("url", "Web URL")],
                default="pdf",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="uploadedpdf",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="uploadedpdf",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="uploadedpdf",
            name="original_filename",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
